trainer:
  gpus: 1
  auto_select_gpus: false
  max_epochs: 30
  deterministic: true

seq_encoder:
    trx_encoder:
      linear_projection_size: 768
      norm_embeddings: false
      embeddings_noise: 0.003
      embeddings: 
        currency: 
          in: 13
          out: 6
        operation_kind: 
          in: 9
          out: 5
        card_type: 
          in: 177
          out: 29
        operation_type: 
          in: 24
          out: 9
        operation_type_group: 
          in: 6
          out: 3
        ecommerce_flag: 
          in: 5
          out: 3
        payment_system: 
          in: 9
          out: 5
        income_flag: 
          in: 5
          out: 5
        mcc: 
          in: 110
          out: 32
        country: 
          in: 26
          out: 9
        city: 
          in: 163
          out: 28
        mcc_category: 
          in: 30
          out: 18
        day_of_week: 
          in: 9
          out: 5
        hour: 
          in: 25
          out: 9
        weekofyear: 
          in: 55
          out: 15
      numeric_values: 
        amnt: identity
        hour_diff: log
    type: gru
    hidden_size: 1024
    bidir: false
    trainable_starter: static
